# SPDX-License-Identifier: LGPL-2.1-or-later
[package]
name = "upse-audio"
description = "Final integer-to-float conversion and PSF playback timeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
