# SPDX-License-Identifier: LGPL-2.1-or-later
[package]
name = "upse-ps1-spu"
description = "Standalone 24-voice PS1 sound processing unit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
upse-ps1-dma = { path = "../dma" }
upse-ps1-irq = { path = "../irq" }
upse-spu-common = { path = "../../shared/spu-common" }

[lints]
workspace = true

[[bench]]
name = "reference_mixer"
harness = false
